### ISSUE TITLE
How to read entire CSV into a variable

### ISSUE THREAD

**Issue by jvence** [tjrantal/CSVtoMat#2]
I have a CSV with no header. I would like to convert it to a .mat file however, I would like to read the entire file into a matrix and assign it to a variable X. How do I do this? I can't seem to assign a variable name and if I try X=load('myfile.mat') it doesn't work.

**Comment by tjrantal** [comment]
X = load('file.mat') should read the .mat to X, so most likely the .mat file you're trying to read is invalid.

You'd have to modify the java code to not expect a header row (perhaps give the headers on the command line or add a row of headers to your file). Look into WriteMat.java lines 31 - 39, and you'll notice that each column needs to have a name. I suspect that if an invalid variable name was used, or  multiple identical names were used the .mat file could become invalid.
